# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, release]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - name: Jest badges generation action
        # You may pin to the exact commit or the version.
        # uses: jpb06/jest-badges-action@60d84d8a877218896d17271edab4abb4182e558c
        uses: jpb06/jest-badges-action@v1.6.0
        with:
          # Branches on which the badges should be generated. Commas separated.
          branches: ci-integration
